server:
  port: 8888
spring:
  application:
    name: new_blog
  datasource:
    url: jdbc:mysql://rm-bp1lf7m05w4ptcljewo.mysql.rds.aliyuncs.com:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: zyz123456#
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    #host:
    host: 43.142.29.233
    port: 6379
    password: zyz123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_